# Base Image
FROM python:3.9-slim

# set working directory
WORKDIR /usr/src/app

# Install build dependencies
RUN apt-get update && apt-get install -y gcc python3-dev libpq-dev

# add and install requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# add .env file
COPY .env /usr/src/app/.env

# add app
COPY . /usr/src/app

# expose port
EXPOSE 5000

# run the application
CMD ["python", "app.py"]
